spring:
  application:
    name: dm-sync-bridge

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.dmsyncbridge: DEBUG

dm:
  sync:
    interval: 10000
    scheduler:
      enabled: true
  databases:
    db-a:
      url: jdbc:dm://192.168.247.202:5236?schema=SYSDBA&clobAsString=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: SYSDBA
      password: Dm123456
      driver-class-name: com.dameng.DmDriver
    db-b:
      url: jdbc:dm://192.168.247.203:5237?schema=SYSDBA&clobAsString=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: SYSDBA
      password: Dm123456
      driver-class-name: com.dameng.DmDriver

management:
  endpoints:
    web:
      exposure:
        include: health,info